services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
    - "webinar:/var/lib/postgresql/data"

  db:
    image: ghcr.io/drsylent/webinar/db:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
  
  api:
    image: ghcr.io/drsylent/webinar/api:latest
    ports:
    - 8080:8080
    environment:
      API_MESSAGE_URL: http://db:8080
      
volumes:
  webinar:
    external: true
