apiVersion: v1
kind: Service
metadata:
  name: {{ include "webinar.fullname" . }}-api
  labels:
    {{- include "webinar.api.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: management
    port: 8081
    protocol: TCP
    targetPort: management
  selector:
    {{- include "webinar.api.selectorLabels" . | nindent 4 }}
  type: {{ .Values.api.service.type | default "ClusterIP" }}
