apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "webinar.fullname" . }}-db
  labels:
    {{- include "webinar.db.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "webinar.db.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: management
    path: /actuator/prometheus
    scheme: http
