apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webinar-api
  labels:
    app: webinar-api
spec:
  selector:
    matchLabels:
      app: webinar-api
  endpoints:
  - port: management
    path: /actuator/prometheus
    scheme: http
