apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: webinar-postgres
    release: webinar
  name: postgres-persistent-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
