apiVersion: v1
kind: Service
metadata:
  labels:
    app: webinar-postgres
  name: webinar-postgres
spec:
  ports:
  - name: jdbc
    port: 5432
    protocol: TCP
    targetPort: jdbc
  selector:
    app: webinar-postgres
  type: ClusterIP
